apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
  namespace: job-queue
spec:
  template:
    spec:
      containers:
        - name: producer
          image: job-queue-producer:latest
          imagePullPolicy: Never
          env:
            - name: JOB_COUNT
              value: "300"
      restartPolicy: Never
  backoffLimit: 2